version: '3.8'

services:
  email-designer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80" # Expose port 3002
    restart: always # Automatically restart the service
