version: '3.8'

services:
  email-designer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"  # Expose port 3002 on the host to port 80 in the container
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    restart: always  # Automatically restart the container if it stops
    # Set the working directory to ensure npm install happens in the right folder
    working_dir: /app
    command: bash -c "npm install && npm run build && npm start"  # Run npm install, build, and start the application
