version: '3.8'

services:
  email-designer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80" # Map port 80 in the container to port 3002 on the host
    restart: always # Restart the container if it stops
