version: '3.8'

services:
  email-designer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always
    command: bash -c "npm install && npm run build && npm start"
