version: '3.8'

services:
  email-designer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"  # Expose port 3002 on the host to port 80 in the container
    environment:
      - NODE_ENV=production
    command: bash -c "npm install && npm run build --prod && npm run start"
    restart: always
