version: '3.8'

services:
  email-designer:
    image: node:18
    container_name: drag-drop-email-designer
    working_dir: /usr/src/app
    ports:
      - "4200:3000"  # Exposes port 3000 of the container to port 4200 on the host
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    command: bash -c "npm install && npm run build && npm run start"
    restart: always  # Ensures the app restarts automatically if it crashes

