version: '3.8'

services:
  email-designer:
    image: node:18
    container_name: drag-drop-email-designer
    working_dir: /usr/src/app
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm run dev"
